mysql:
  host: localhost
  port: 3306
  user: root
  password: root
  database: gorm

server:
  host: 127.0.0.1
  port: 8080

ldap:
  enabled: true
  url: localhost
  port: 10389
  managerDN: uid=admin,ou=system
  managerPassword: secret
  userSearchBase: dc=example,dc=com
  loginAttribute: uid
  mailAttribute: mail