mysql:
  host: localhost
  port: 3306
  user: root
  password: root
  database: gorm

server:
  host: 127.0.0.1
  port: 8080

ldap:
  enabled: false
  url: ldap://localhost:10389
  managerDN: uid=admin,ou=system
  managerPassword: secret
  userSearchBase: dc=example,dc=com
  loginAttribute: uid
  mailAttribute: mail
  insecureSkipVerify: true

redis:
    host: localhost
    port: 6379
    password: ""

email:
  address: smtp.qq.com:25
  count: 5
  username: 1665400978@qq.com
  password: srwrbfpblphtbcac
  host: smtp.qq.com